/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  UintUtils,
  UintUtilsInterface,
} from "../../../../@solidstate/contracts/utils/UintUtils";

const _abi = [
  {
    inputs: [],
    name: "UintUtils__InsufficientPadding",
    type: "error",
  },
  {
    inputs: [],
    name: "UintUtils__InvalidBase",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220be493d282a6a3c14120d9748477f8c7d38161804396a6727c27f8633f9cbe58864736f6c63430008140033";

type UintUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UintUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UintUtils__factory extends ContractFactory {
  constructor(...args: UintUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UintUtils> {
    return super.deploy(overrides || {}) as Promise<UintUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UintUtils {
    return super.attach(address) as UintUtils;
  }
  override connect(signer: Signer): UintUtils__factory {
    return super.connect(signer) as UintUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UintUtilsInterface {
    return new utils.Interface(_abi) as UintUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UintUtils {
    return new Contract(address, _abi, signerOrProvider) as UintUtils;
  }
}
