/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { BTLY } from "./BTLY";
export type { Bank } from "./Bank";
export type { BitlyExchange } from "./BitlyExchange";
export type { TokenExchange } from "./TokenExchange";
