/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as btlySol from "./BTLY.sol";
export type { btlySol };
import type * as bankSol from "./Bank.sol";
export type { bankSol };
import type * as bitlyExchangeSol from "./BitlyExchange.sol";
export type { bitlyExchangeSol };
import type * as proxyAdminSol from "./ProxyAdmin.sol";
export type { proxyAdminSol };
import type * as tokenExchangeSol from "./TokenExchange.sol";
export type { tokenExchangeSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as tests from "./tests";
export type { tests };
export type { Marketplace } from "./Marketplace";
