/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export { E1155__factory } from "./E1155__factory";
export { E721__factory } from "./E721__factory";
